name: notification

on:
  workflow_run:
    workflows:
      - cd
    types:
      - completed

env:
  SLACK-CHANNEL: '#mi-connectors-notifications'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - name: Send CI/CD pipeline success message
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ env.SLACK_TOKEN }}
          slack-channel: ${{ env.SLACK-CHANNEL }}
          slack-text: |
            :beers: ${{ github.repository }} successfully published to market place! More information@ ${{ github.event.workflow_run.html_url }}

      - name: Send CI/CD pipeline failure message
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ env.SLACK_TOKEN }}
          slack-channel: ${{ env.SLACK-CHANNEL }}
          slack-text: |
            :no_entry_sign: ${{ github.repository }} failed to publish to market place! More information@ ${{ github.event.workflow_run.html_url }}
